language: node_js
node_js:
  - '8'
  - '6'
script:
  - npm run test
  - npm run build
branches:
  only:
    - master
deploy:
  provider: npm
  email: "emish89@yahoo.it"
  api_key: "$NPM_TOKEN"
  skip_cleanup: true
  on:
    tags: true    
install:
  - npm install -g codecov
script:
  - codecov
