language: node_js
node_js:
  - '8'
  - '6'
script:
  - npm run test
  - npm run build
branches:
  only:
    - master
before_install:
  - npm i -g makeshift && makeshift -s @bcoe -r registry.npmjs.org    
install:
  - npm install -g codecov
script:
  - codecov
deploy:
  provider: npm
  email: emish89@yahoo.it
  api_key: $NPM_TOKEN
  on:
    tags: true